export type Tier = 'A' | 'B' | 'C';
export type Coverage = 'strong' | 'partial' | 'missing';
export type FilterKey = 'ego' | 'egoExo' | 'audio' | 'multimodal' | 'hourRecording' | 'crossDay' | 'crossWeek' | 'memory' | 'openQA' | 'temporal' | 'accessible';

export type Dataset = {
  name: string; year: number; tier: Tier; perspective: string; modalities: string[]; audio: string;
  participants: string; maxClip: string; totalHours: string; hoursValue: number; span: string; spanDays: number;
  continuity: string; memoryTasks: string; annotations: string; access: string; status: '已公开' | '需要申请' | '部分公开' | '未确认';
  similarity: string; difference: string; url: string; similarityScore: number; memoryScore: number;
  flags: Record<FilterKey, boolean>;
};

const f = (values: Partial<Record<FilterKey, boolean>>): Record<FilterKey, boolean> => ({
  ego:false, egoExo:false, audio:false, multimodal:false, hourRecording:false, crossDay:false, crossWeek:false, memory:false, openQA:false, temporal:false, accessible:false, ...values,
});

export const datasets: Dataset[] = [
  { name:'CASTLE 2024', year:2025, tier:'A', perspective:'10 路第一视角 + 5 路固定第三视角，同步', modalities:['UHD RGB','每路音频','IMU/GPS','Fitbit/biometric','个人图片'], audio:'有', participants:'10 名佩戴者 / 12 名志愿者；同一房屋与外出社交', maxClip:'严格对齐的 1 h 文件；每设备每日 7–12 h', totalHours:'600+ camera-hours', hoursValue:600, span:'连续 4 天', spanDays:4, continuity:'日内长时；非 24 h', memoryTasks:'全库事件/物体实例检索；开放 QA；185 MCQ', annotations:'ASR、query、视角/时间证据', access:'Hugging Face 可下载；CC BY-NC-SA 4.0 标签与条款存在冲突', status:'已公开', similarity:'多人同住数日、同步 ego+fixed exo、全程音频与传感器；采集结构最像', difference:'4 天而非 7 天；初始语义标注较少', url:'https://castle-dataset.github.io/', similarityScore:99, memoryScore:91, flags:f({ego:true,egoExo:true,audio:true,multimodal:true,hourRecording:true,crossDay:true,memory:true,openQA:true,temporal:true,accessible:true}) },
  { name:'EgoMonth', year:2026, tier:'A', perspective:'仅第一视角', modalities:['RGB','QA','metadata'], audio:'采集但默认静音/移除', participants:'20 人；学习、工作、交通、购物、家务', maxClip:'平均 24.5 min；最大未确认', totalHours:'301 h', hoursValue:301, span:'每人 20–120 天', spanDays:120, continuity:'间歇采样，计划约 0.5 h/天', memoryTasks:'schema consolidation、episodic indexing、cascading reasoning；14 tasks / 1,443 MCQ', annotations:'人工题、选项、跨 session evidence', access:'research-only；QA/样例可见，原始视频需额外审批', status:'需要申请', similarity:'同一人物长日历、真实生活、严格跨视频记忆', difference:'无第三视角；音频不稳定；非群体共同叙事', url:'https://arxiv.org/html/2608.13113', similarityScore:92, memoryScore:99, flags:f({ego:true,multimodal:true,crossDay:true,crossWeek:true,memory:true,temporal:true}) },
  { name:'HD-EPIC', year:2025, tier:'A', perspective:'仅第一视角', modalities:['Aria RGB','7-mic audio','gaze','SLAM/pose','point cloud','3D twin'], audio:'有', participants:'9 人 / 9 个家庭厨房', maxClip:'视频均值 15.9±14.5 min；最长 recipe 跨 2 d 6 h', totalHours:'41.3 h', hoursValue:41.3, span:'至少连续 3 天/人', spanDays:3, continuity:'进厨房录、离开停；非全天', memoryTasks:'VQA、recipe、物体 itinerary、状态与程序记忆', annotations:'动作、声音、物体轨迹、3D、手、眼动', access:'MP4/VRS/audio/SLAM/gaze/twin/annotations 可下载；CC BY-NC 4.0', status:'已公开', similarity:'跨天、音频、极密标注、跨视频物体状态链', difference:'厨房单域、仅 ego、每人累计 3.5–7.2 h', url:'https://hd-epic.github.io/site/', similarityScore:88, memoryScore:94, flags:f({ego:true,audio:true,multimodal:true,crossDay:true,memory:true,temporal:true,accessible:true}) },
  { name:'TeleEgo', year:2025, tier:'A', perspective:'仅第一视角', modalities:['video','同步 audio','ASR','visual narration'], audio:'有', participants:'5 人；工作/学习、日常、社交、外出', maxClip:'每人合并历史均值 14.4 h；文件级最大未报告', totalHours:'70+ h', hoursValue:70, span:'连续 3 天/人', spanDays:3, continuity:'日内连续片段；非 72 h/人', memoryTasks:'3 dimensions / 12 subtasks；RTA；MPT', annotations:'3,291 QA、evidence timestamp、required modality', access:'HF 五人视频/QA/timeline；research-only；代码 MIT', status:'已公开', similarity:'三日真实 ego 音视频、ASR/narration、助手式 QA', difference:'题目证据主要 10–60 min，严格跨天题较少', url:'https://teleai-uagi.github.io/TeleEgo/', similarityScore:90, memoryScore:86, flags:f({ego:true,audio:true,multimodal:true,hourRecording:true,crossDay:true,memory:true,openQA:true,temporal:true,accessible:true}) },
  { name:'MM-Lifelong', year:2026, tier:'A', perspective:'混合；Week 复用 EgoLife，Month 为 IRL livestream', modalities:['同步视觉','音频','QA'], audio:'有', participants:'Day / Week / Month 三条 lifelog', maxClip:'23.6 / 51.9 / 105.6 h 观测总量', totalHours:'181.1 h', hoursValue:181.1, span:'约 24 h / 7 d / 51 d', spanDays:51, continuity:'来源混合；Week/Month 为跨日历史', memoryTasks:'needle-in-lifestream、跨小时/日 multi-hop', annotations:'1,289 QA；evidence retrieval', access:'GitHub 声称发布；HF 匿名访问状态不一致', status:'部分公开', similarity:'明确区分观测时长与物理跨度；跨日音视频', difference:'Week 直接复用 EgoLife；Month 不是 wearable ego', url:'https://arxiv.org/html/2603.05484', similarityScore:89, memoryScore:98, flags:f({ego:true,audio:true,multimodal:true,hourRecording:true,crossDay:true,crossWeek:true,memory:true,openQA:true,temporal:true}) },
  { name:'EgoStream', year:2026, tier:'B', perspective:'源数据均为第一视角', modalities:['统一视觉输入','源数据继承标注'], audio:'不统一', participants:'重组 Ego4D-VQA、EgoLife、EgoTempo、Multi-Hop EgoQA、HD-EPIC', maxClip:'以 recall delay 定义；含 >8 h 桶', totalHours:'无新增 raw hours', hoursValue:0, span:'最长由 EgoLife 跨日样本贡献', spanDays:7, continuity:'严格 streaming protocol；源视频不一', memoryTasks:'七类 memory / 七个 recall regimes / 遗忘评测', annotations:'2,250 QA → 8,528 recall evaluations；AVW', access:'论文称 annotation/code/eval 发布；匿名可见性需复核', status:'部分公开', similarity:'直接吸收 433 道 EgoLife 题并控制记忆延迟', difference:'没有新增原始生活记录；多源模态不统一', url:'https://arxiv.org/html/2605.31557', similarityScore:86, memoryScore:97, flags:f({ego:true,multimodal:true,hourRecording:true,crossDay:true,memory:true,temporal:true}) },
  { name:'Ego4D', year:2022, tier:'B', perspective:'主要第一视角；少量同步 wearable', modalities:['RGB','部分 audio','gaze','IMU','stereo/3D','narration'], audio:'部分有', participants:'官方版本 923/926/931 人；74 locations / 9 countries', maxClip:'典型 raw clip ≈8 min；NLQ 最大 20 min', totalHours:'3,670 h', hoursValue:3670, span:'未报告统一同人跨日协议', spanDays:0, continuity:'多人多短片，不是纵向流', memoryTasks:'NLQ、VQ、MQ episodic memory；forecasting / AV diarization', annotations:'约 74K queries / 800 h annotated', access:'需接受 Ego4D License；大包 7–30+ TB', status:'需要申请', similarity:'大规模真实第一视角、episodic retrieval、音频与社会任务', difference:'同人跨日协议缺失；canonical clips 8–20 min', url:'https://ego4d-data.org/', similarityScore:75, memoryScore:72, flags:f({ego:true,audio:true,multimodal:true,memory:true,temporal:true}) },
  { name:'Ego-Exo4D V2', year:2024, tier:'B', perspective:'Aria 第一视角 + 通常 4–5 路固定第三视角，同步标定', modalities:['RGB','7-ch audio','SLAM','双 IMU','gaze','pose','3D point cloud'], audio:'有', participants:'740 wearers / 123 sites / 13 cities / 5,035 takes', maxClip:'1–42 min', totalHours:'1,286.3 camera-hours；221.26 ego-hours', hoursValue:1286.3, span:'无统一跨日同人协议', spanDays:0, continuity:'take 级连续', memoryTasks:'keystep、task graph、ego-exo correspondence / view translation', annotations:'action/narration、mask、2D/3D pose、procedure graph', access:'申请 Ego4D License 后 CLI 下载', status:'需要申请', similarity:'最强同步/标定 ego-exo 与传感器组合', difference:'技能演示 1–42 min；非共同生活、非跨天记忆', url:'https://discuss.ego4d-data.org/t/ego-exo4d-v2-full-ego-exo4d-release/552', similarityScore:82, memoryScore:65, flags:f({ego:true,egoExo:true,audio:true,multimodal:true,temporal:true}) },
  { name:'HoloAssist', year:2023, tier:'B', perspective:'仅第一视角；third-person annotation 不是 exo video', modalities:['RGB','depth','head/hand pose','gaze','audio','IMU','ASR'], audio:'有', participants:'222 人 / 350 instructor-performer pairs / 20 tasks', maxClip:'约 2,221 sessions；最大未确认', totalHours:'166 h', hoursValue:166, span:'未报告跨天', spanDays:0, continuity:'task session 级', memoryTasks:'动作识别/预测、mistake/intervention、hand forecasting', annotations:'conversation/ASR、粗细动作、错误、干预、摘要', access:'数据、传感器、splits 已发布；CDLA v2', status:'已公开', similarity:'带语音的第一视角互动助手、多传感器', difference:'受控任务 session；无 exo 或跨天', url:'https://holoassist.github.io/data_links/README.html', similarityScore:72, memoryScore:58, flags:f({ego:true,audio:true,multimodal:true,temporal:true,accessible:true}) },
  { name:'EgoCom', year:2020, tier:'B', perspective:'2–3 路同步第一视角；无固定第三视角', modalities:['1080p video','双声道 embodied audio','word timestamp','speaker labels'], audio:'有', participants:'34 speakers；三人对话；repo 39 / 论文 28 conversations', maxClip:'5 min clips 或 15–30 min 完整对话', totalHours:'38.5 camera-hours；约 14 h 独特对话', hoursValue:38.5, span:'采集日历未确认', spanDays:0, continuity:'对话 session 级', memoryTasks:'turn-taking、transcription、speaker ID、source separation/localization', annotations:'word timestamp、speaker labels、AVT features', access:'repo 可直接下载；数据本体许可名需核对', status:'已公开', similarity:'多人同步第一视角、对话与社会关系', difference:'无长期记忆 QA；自然跨度未知', url:'https://github.com/facebookresearch/EgoCom-Dataset', similarityScore:70, memoryScore:51, flags:f({ego:true,audio:true,multimodal:true,accessible:true}) },
  { name:'SAYCam', year:2021, tier:'B', perspective:'婴幼儿头戴第一视角', modalities:['audiovisual','部分 transcript','location/activity/object 标签','发展报告'], audio:'有', participants:'3 名儿童', maxClip:'session 通常 1–2 h；文件最大未确认', totalHours:'>415 h 至 500+ h（版本不同）', hoursValue:500, span:'每人约 2–2.5 年', spanDays:913, continuity:'每周约 2 h，长期规则抽样', memoryTasks:'表征学习、语言/视觉发展；可二次标注长期记忆', annotations:'transcript、地点/活动/生物/身体/物体、月度发展', access:'Databrary/OSF；研究账户与协议；未模糊眼部视频受限', status:'需要申请', similarity:'多年同人视觉与语音历史', difference:'幼儿域、稀疏抽样、无正式 memory QA / exo', url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC8412186/', similarityScore:78, memoryScore:84, flags:f({ego:true,audio:true,multimodal:true,hourRecording:true,crossDay:true,crossWeek:true}) },
  { name:'KrishnaCam', year:2016, tier:'C', perspective:'单人第一视角', modalities:['RGB','GPS','acceleration','body orientation'], audio:'无', participants:'1 名研究生', maxClip:'约 460 sequences；最大未确认', totalHours:'70 h', hoursValue:70, span:'9 个月', spanDays:274, continuity:'间歇录像', memoryTasks:'daily novelty、future trajectory、long-term scene change', annotations:'GPS/motion 与图像序列', access:'作者 Drive 链可见；许可未确认', status:'部分公开', similarity:'同一成年人跨 9 个月，适合 continual / personalization', difference:'单人、无音频/语言/QA/exo，稀疏且较旧', url:'https://krsingh.cs.ucdavis.edu/krishna_files/papers/krishnacam/krishnacam.html', similarityScore:62, memoryScore:76, flags:f({ego:true,multimodal:true,crossDay:true,crossWeek:true}) },
  { name:'M3-Bench', year:2026, tier:'C', perspective:'机器人/头戴第一视角 + web videos', modalities:['video','environment/spatial audio','lav mic','transcript','speaker ID'], audio:'有', participants:'100 新录 robot-perspective + 920 web videos', maxClip:'Robot 均值 34.0 min；Web 均值 27.2 min', totalHours:'约 473.4 h（数量×均值推算）', hoursValue:473.4, span:'无跨天主体协议', spanDays:0, continuity:'单 session', memoryTasks:'multi-evidence / multi-hop / cross-modal / person understanding', annotations:'4,490 open-ended QA；GPT-4o judge', access:'Robot video/annotations 公开；Web 多为 URL；代码 Apache-2.0', status:'部分公开', similarity:'强对话、speaker、环境音与多证据记忆', difference:'无跨天主体；部分不是第一视角；web 链接可失效', url:'https://m3-agent.github.io/', similarityScore:65, memoryScore:71, flags:f({ego:true,audio:true,multimodal:true,openQA:true,temporal:true,accessible:true}) },
  { name:'LongShOTBench', year:2026, tier:'C', perspective:'Web videos；非专门第一视角', modalities:['visual','speech','non-speech audio'], audio:'有', participants:'274 videos，多领域', maxClip:'7.8–89.7 min；均值约 41 min', totalHours:'约 188 h', hoursValue:188, span:'无自然跨天主体协议', spanDays:0, continuity:'单视频', memoryTasks:'单/多轮 intent-driven omni-modal long-video QA', annotations:'3,401 samples / 4,893 turns；weighted rubric', access:'HF / 代码公开；CC BY-NC-SA 4.0，源视频许可继承', status:'已公开', similarity:'视觉、语音、环境音，适合开放式助手评测', difference:'非日常第一视角或跨天；最长不足 90 min', url:'https://longshot.cvmbzuai.com/', similarityScore:54, memoryScore:61, flags:f({audio:true,multimodal:true,openQA:true,temporal:true,accessible:true}) },
  { name:'FindingDory', year:2025, tier:'C', perspective:'具身智能体第一视角', modalities:['RGB-D','pose','GPS-compass','actions'], audio:'无', participants:'Habitat 模拟环境；1,478 train + 100 val episodes', maxClip:'400–3,500 frames；fps 未确认', totalHours:'未报告可比小时', hoursValue:0, span:'“yesterday”为 episode 内设定', spanDays:0, continuity:'两阶段 episode', memoryTasks:'观察历史后在重排环境中找物/操作', annotations:'object state/location、trajectory、semantic coverage', access:'HF 约 32.5 GB；Apache-2.0', status:'已公开', similarity:'严格测试 agent 是否记住先前物体状态', difference:'模拟、无音频/人际关系；不是现实跨天', url:'https://findingdorybenchmark.github.io/', similarityScore:51, memoryScore:74, flags:f({ego:true,multimodal:true,memory:true,temporal:true,accessible:true}) },
];

export const capabilityRows: { name:string; values: Coverage[] }[] = [
  { name:'EgoMonth', values:['strong','partial','strong','strong','partial','strong','missing','missing','strong'] },
  { name:'CASTLE', values:['strong','strong','strong','partial','strong','partial','strong','strong','strong'] },
  { name:'HD-EPIC', values:['strong','missing','strong','strong','strong','strong','missing','missing','strong'] },
  { name:'TeleEgo', values:['strong','strong','strong','partial','strong','partial','missing','partial','strong'] },
  { name:'MM-Lifelong', values:['strong','partial','partial','partial','strong','strong','missing','strong','strong'] },
  { name:'Ego4D + Ego-Exo4D', values:['strong','partial','strong','strong','strong','missing','strong','partial','strong'] },
  { name:'HoloAssist + EgoCom', values:['partial','strong','missing','partial','strong','missing','missing','missing','strong'] },
  { name:'M3 + LongShOT', values:['strong','strong','partial','partial','strong','missing','missing','strong','partial'] },
  { name:'FindingDory', values:['partial','missing','strong','strong','missing','missing','missing','missing','strong'] },
];

export const sources = [
  ['EgoLife · CVPR 2025 paper','https://openaccess.thecvf.com/content/CVPR2025/html/Yang_EgoLife_Towards_Egocentric_Life_Assistant_CVPR_2025_paper.html'],
  ['EgoLife · supplement','https://openaccess.thecvf.com/content/CVPR2025/supplemental/Yang_EgoLife_Towards_Egocentric_CVPR_2025_supplemental.pdf'],
  ['EgoLife · official blog','https://egolife-ai.github.io/blog/'],
  ['EgoLife · project','https://egolife-ai.github.io/'], ['EgoLife · GitHub','https://github.com/EvolvingLMMs-Lab/EgoLife'],
  ['EgoLife · Hugging Face','https://huggingface.co/datasets/lmms-lab/EgoLife'], ['Ego-R1','https://egolife-ai.github.io/Ego-R1/'],
  ['CASTLE','https://castle-dataset.github.io/'], ['EgoMonth','https://arxiv.org/html/2608.13113'], ['HD-EPIC','https://hd-epic.github.io/site/'],
  ['TeleEgo','https://teleai-uagi.github.io/TeleEgo/'], ['MM-Lifelong','https://arxiv.org/html/2603.05484'], ['EgoStream','https://arxiv.org/html/2605.31557'],
  ['Ego4D','https://ego4d-data.org/'], ['Ego-Exo4D V2','https://discuss.ego4d-data.org/t/ego-exo4d-v2-full-ego-exo4d-release/552'],
  ['HoloAssist','https://holoassist.github.io/data_links/README.html'], ['EgoCom','https://github.com/facebookresearch/EgoCom-Dataset'],
  ['SAYCam','https://pmc.ncbi.nlm.nih.gov/articles/PMC8412186/'], ['KrishnaCam','https://krsingh.cs.ucdavis.edu/krishna_files/papers/krishnacam/krishnacam.html'],
  ['M3-Bench','https://m3-agent.github.io/'], ['LongShOTBench','https://longshot.cvmbzuai.com/'], ['FindingDory','https://findingdorybenchmark.github.io/'],
] as const;
